<?php

namespace App\Support;

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\File;

class Installer
{
    public const LOCK_FILE = 'installed';

    /**
     * Every .env key Alternova needs for shared-hosting production.
     * Secrets the buyer configures in Admin (mail, GitHub) stay empty / log.
     *
     * @return array<string, string>
     */
    public static function recommendedEnvDefaults(): array
    {
        $appUrl = self::detectAppUrl();
        $fromHost = parse_url($appUrl, PHP_URL_HOST) ?: 'example.com';

        return [
            // App
            'APP_ENV' => 'production',
            'APP_DEBUG' => 'false',
            'APP_URL' => $appUrl,
            'LOG_CHANNEL' => 'stack',
            'LOG_LEVEL' => 'error',

            // Drivers tuned for Hostinger / shared hosts (no Redis required)
            'BROADCAST_DRIVER' => 'log',
            'CACHE_DRIVER' => 'file',
            'CACHE_STORE' => 'file',
            'FILESYSTEM_DISK' => 'local',
            'QUEUE_CONNECTION' => 'database',
            'SESSION_DRIVER' => 'database',
            'SESSION_LIFETIME' => '480',
            'SESSION_HTTP_ONLY' => 'true',
            'SESSION_SAME_SITE' => 'lax',
            // Do NOT force SESSION_SECURE_COOKIE — leave unset so Laravel matches HTTPS detection

            // Search (collection = no Meilisearch required)
            'SCOUT_DRIVER' => 'collection',

            // Mail defaults (buyer can override in Admin → Mail)
            'MAIL_MAILER' => 'log',
            'MAIL_HOST' => '127.0.0.1',
            'MAIL_PORT' => '2525',
            'MAIL_USERNAME' => '',
            'MAIL_PASSWORD' => '',
            'MAIL_ENCRYPTION' => '',
            'MAIL_FROM_ADDRESS' => 'noreply@'.$fromHost,
            'MAIL_FROM_NAME' => '"${APP_NAME}"',

            // Optional integrations — configured in Admin, not required in .env
            'GITHUB_TOKEN' => '',
        ];
    }

    /**
     * @deprecated Use recommendedEnvDefaults()
     *
     * @return array<string, string>
     */
    public static function performanceEnvDefaults(): array
    {
        return self::recommendedEnvDefaults();
    }

    public static function lockPath(): string
    {
        return storage_path('app/'.self::LOCK_FILE);
    }

    public static function isInstalled(): bool
    {
        return File::exists(self::lockPath());
    }

    public static function lock(): void
    {
        File::ensureDirectoryExists(dirname(self::lockPath()));
        File::put(self::lockPath(), json_encode([
            'installed_at' => now()->toIso8601String(),
            'version' => '1.0.0',
        ], JSON_PRETTY_PRINT));
    }

    public static function unlock(): void
    {
        if (File::exists(self::lockPath())) {
            File::delete(self::lockPath());
        }
    }

    /**
     * Full production-ready .env body. Used when creating or resetting .env.
     *
     * @param  array<string, string>  $overrides
     */
    public static function defaultEnvContent(array $overrides = []): string
    {
        $defaults = [
            'APP_NAME' => 'Alternova',
            'APP_ENV' => 'production',
            'APP_KEY' => '',
            'APP_DEBUG' => 'false',
            'APP_URL' => 'http://localhost',
            'LOG_CHANNEL' => 'stack',
            'LOG_LEVEL' => 'error',
            'DB_CONNECTION' => 'mysql',
            'DB_HOST' => '127.0.0.1',
            'DB_PORT' => '3306',
            'DB_DATABASE' => '',
            'DB_USERNAME' => '',
            'DB_PASSWORD' => '',
            'BROADCAST_DRIVER' => 'log',
            'CACHE_DRIVER' => 'file',
            'CACHE_STORE' => 'file',
            'FILESYSTEM_DISK' => 'local',
            'QUEUE_CONNECTION' => 'sync',
            'SESSION_DRIVER' => 'file',
            'SESSION_LIFETIME' => '480',
            'SESSION_HTTP_ONLY' => 'true',
            'SESSION_SAME_SITE' => 'lax',
            'SCOUT_DRIVER' => 'collection',
            'MAIL_MAILER' => 'log',
            'MAIL_HOST' => '127.0.0.1',
            'MAIL_PORT' => '2525',
            'MAIL_USERNAME' => '',
            'MAIL_PASSWORD' => '',
            'MAIL_ENCRYPTION' => '',
            'MAIL_FROM_ADDRESS' => 'hello@example.com',
            'MAIL_FROM_NAME' => '"${APP_NAME}"',
            'GITHUB_TOKEN' => '',
        ];

        $values = array_merge($defaults, $overrides);

        if (empty($values['APP_KEY'])) {
            $values['APP_KEY'] = 'base64:'.base64_encode(random_bytes(32));
        }

        $lines = [
            '# Alternova — generated by installer (safe shared-hosting defaults)',
            'APP_NAME='.self::envValue($values['APP_NAME']),
            'APP_ENV='.$values['APP_ENV'],
            'APP_KEY='.$values['APP_KEY'],
            'APP_DEBUG='.$values['APP_DEBUG'],
            'APP_URL='.$values['APP_URL'],
            '',
            'LOG_CHANNEL='.$values['LOG_CHANNEL'],
            'LOG_LEVEL='.$values['LOG_LEVEL'],
            '',
            'DB_CONNECTION='.$values['DB_CONNECTION'],
            'DB_HOST='.$values['DB_HOST'],
            'DB_PORT='.$values['DB_PORT'],
            'DB_DATABASE='.self::envValue($values['DB_DATABASE']),
            'DB_USERNAME='.self::envValue($values['DB_USERNAME']),
            'DB_PASSWORD='.self::envValue($values['DB_PASSWORD']),
            '',
            'BROADCAST_DRIVER='.$values['BROADCAST_DRIVER'],
            'CACHE_DRIVER='.$values['CACHE_DRIVER'],
            'CACHE_STORE='.$values['CACHE_STORE'],
            'FILESYSTEM_DISK='.$values['FILESYSTEM_DISK'],
            'QUEUE_CONNECTION='.$values['QUEUE_CONNECTION'],
            'SESSION_DRIVER='.$values['SESSION_DRIVER'],
            'SESSION_LIFETIME='.$values['SESSION_LIFETIME'],
            'SESSION_HTTP_ONLY='.$values['SESSION_HTTP_ONLY'],
            'SESSION_SAME_SITE='.$values['SESSION_SAME_SITE'],
            '',
            'SCOUT_DRIVER='.$values['SCOUT_DRIVER'],
            '',
            'MAIL_MAILER='.$values['MAIL_MAILER'],
            'MAIL_HOST='.$values['MAIL_HOST'],
            'MAIL_PORT='.$values['MAIL_PORT'],
            'MAIL_USERNAME='.self::envValue($values['MAIL_USERNAME']),
            'MAIL_PASSWORD='.self::envValue($values['MAIL_PASSWORD']),
            'MAIL_ENCRYPTION='.$values['MAIL_ENCRYPTION'],
            'MAIL_FROM_ADDRESS='.self::envValue($values['MAIL_FROM_ADDRESS']),
            'MAIL_FROM_NAME='.$values['MAIL_FROM_NAME'],
            '',
            '# Optional — prefer Admin → Integrations for GitHub token',
            'GITHUB_TOKEN='.self::envValue($values['GITHUB_TOKEN']),
        ];

        return implode("\n", $lines)."\n";
    }

    protected static function envValue(string $value): string
    {
        if ($value === '') {
            return '';
        }

        if (preg_match('/\s|#|"|\'|=/', $value)) {
            return '"'.str_replace(['\\', '"'], ['\\\\', '\\"'], $value).'"';
        }

        return $value;
    }

    public static function ensureEnvFile(): bool
    {
        $envPath = base_path('.env');

        if (! File::exists($envPath)) {
            File::put($envPath, self::defaultEnvContent([
                'APP_URL' => self::detectAppUrl(),
            ]));

            return true;
        }

        $content = File::get($envPath);

        if (! preg_match('/^DB_CONNECTION=/m', $content)) {
            $key = '';
            if (preg_match('/^APP_KEY=(.+)$/m', $content, $m)) {
                $key = trim($m[1]);
            }

            File::put($envPath, self::defaultEnvContent([
                'APP_KEY' => $key,
                'APP_URL' => self::detectAppUrl(),
            ]));
        }

        return true;
    }

    public static function detectAppUrl(): string
    {
        if (! empty($_SERVER['HTTP_HOST'])) {
            $scheme = (! empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
                || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https')
                ? 'https'
                : 'http';

            return $scheme.'://'.$_SERVER['HTTP_HOST'];
        }

        return 'http://localhost';
    }

    /**
     * Write / update keys. Always merges recommended production defaults first,
     * then $values (so caller can override).
     *
     * @param  array<string, string>  $values
     */
    public static function writeEnv(array $values): void
    {
        self::ensureEnvFile();

        $envPath = base_path('.env');
        $content = File::get($envPath);

        $values = array_merge(self::recommendedEnvDefaults(), $values);

        foreach ($values as $key => $value) {
            $value = (string) $value;
            $formatted = self::envValue($value);

            if (preg_match("/^{$key}=.*/m", $content)) {
                $content = preg_replace(
                    "/^{$key}=.*/m",
                    "{$key}={$formatted}",
                    $content
                );
            } else {
                $content = rtrim($content)."\n{$key}={$formatted}\n";
            }
        }

        File::put($envPath, $content);
    }

    /**
     * Add any missing recommended keys without overwriting existing values.
     * Useful for upgrades of sites that already have a partial .env.
     */
    public static function ensureRecommendedKeys(): void
    {
        self::ensureEnvFile();

        $envPath = base_path('.env');
        $content = File::get($envPath);
        $defaults = self::recommendedEnvDefaults();
        $appended = false;

        foreach ($defaults as $key => $value) {
            if (preg_match("/^{$key}=/m", $content)) {
                continue;
            }
            $content = rtrim($content)."\n{$key}=".self::envValue((string) $value)."\n";
            $appended = true;
        }

        // Always force critical production safety + performance keys after install
        $force = [
            'APP_ENV' => 'production',
            'APP_DEBUG' => 'false',
            'LOG_LEVEL' => 'error',
            'CACHE_DRIVER' => 'file',
            'CACHE_STORE' => 'file',
            'SESSION_DRIVER' => 'database',
            'SESSION_LIFETIME' => '480',
            'SESSION_HTTP_ONLY' => 'true',
            'SESSION_SAME_SITE' => 'lax',
            'QUEUE_CONNECTION' => 'database',
            'SCOUT_DRIVER' => 'collection',
            'BROADCAST_DRIVER' => 'log',
            'FILESYSTEM_DISK' => 'local',
        ];

        foreach ($force as $key => $value) {
            $formatted = self::envValue((string) $value);
            if (preg_match("/^{$key}=.*/m", $content)) {
                $content = preg_replace("/^{$key}=.*/m", "{$key}={$formatted}", $content);
            } else {
                $content = rtrim($content)."\n{$key}={$formatted}\n";
            }
        }

        File::put($envPath, $content);

        if ($appended) {
            // no-op; kept for clarity
        }
    }

    /**
     * Apply full recommended .env after migrations (sessions/jobs tables exist).
     */
    public static function applyRecommendedEnv(): void
    {
        self::ensureRecommendedKeys();
        self::writeEnv(self::recommendedEnvDefaults());

        try {
            Artisan::call('config:clear');
        } catch (\Throwable) {
        }
    }

    /**
     * @deprecated Use applyRecommendedEnv()
     */
    public static function applyPerformanceEnv(): void
    {
        self::applyRecommendedEnv();
    }

    /**
     * Until migrations finish, never use database cache/sessions.
     * Laravel 11 reads CACHE_STORE (not only CACHE_DRIVER). A missing `cache`
     * or `sessions` table resets the wizard and throws on SiteSetting cache reads.
     */
    public static function ensureInstallSafeDrivers(): void
    {
        if (self::isInstalled()) {
            return;
        }

        self::ensureEnvFile();
        $envPath = base_path('.env');
        $content = File::get($envPath);
        $force = [
            'CACHE_DRIVER' => 'file',
            'CACHE_STORE' => 'file',
            'SESSION_DRIVER' => 'file',
            'QUEUE_CONNECTION' => 'sync',
        ];
        foreach ($force as $key => $value) {
            if (preg_match("/^{$key}=.*/m", $content)) {
                $content = preg_replace("/^{$key}=.*/m", "{$key}={$value}", $content);
            } else {
                $content = rtrim($content)."\n{$key}={$value}\n";
            }
        }
        File::put($envPath, $content);
    }

    public static function ensureAppKey(): string

    {
        self::ensureEnvFile();

        $envPath = base_path('.env');
        $content = File::get($envPath);

        if (preg_match('/^APP_KEY=(.+)$/m', $content, $m) && trim($m[1]) !== '') {
            return trim($m[1]);
        }

        $key = 'base64:'.base64_encode(random_bytes(32));
        self::writeEnv(['APP_KEY' => $key]);

        return $key;
    }

    public static function ensureStorageDirectories(): void
    {
        $dirs = [
            storage_path('app'),
            storage_path('app/public'),
            storage_path('framework'),
            storage_path('framework/cache'),
            storage_path('framework/cache/data'),
            storage_path('framework/sessions'),
            storage_path('framework/views'),
            storage_path('logs'),
            base_path('bootstrap/cache'),
        ];

        foreach ($dirs as $dir) {
            if (! is_dir($dir)) {
                @mkdir($dir, 0775, true);
            }
        }
    }

    public static function requirements(): array
    {
        self::ensureStorageDirectories();

        return [
            'php_version' => [
                'label' => 'PHP >= 8.2',
                'ok' => version_compare(PHP_VERSION, '8.2.0', '>='),
                'value' => PHP_VERSION,
            ],
            'pdo' => [
                'label' => 'PDO MySQL or PostgreSQL',
                'ok' => extension_loaded('pdo_mysql') || extension_loaded('pdo_pgsql'),
                'value' => extension_loaded('pdo_mysql')
                    ? 'pdo_mysql'
                    : (extension_loaded('pdo_pgsql') ? 'pdo_pgsql' : 'missing'),
            ],
            'openssl' => [
                'label' => 'OpenSSL',
                'ok' => extension_loaded('openssl'),
                'value' => extension_loaded('openssl') ? 'ok' : 'missing',
            ],
            'mbstring' => [
                'label' => 'Mbstring',
                'ok' => extension_loaded('mbstring'),
                'value' => extension_loaded('mbstring') ? 'ok' : 'missing',
            ],
            'tokenizer' => [
                'label' => 'Tokenizer',
                'ok' => extension_loaded('tokenizer'),
                'value' => extension_loaded('tokenizer') ? 'ok' : 'missing',
            ],
            'json' => [
                'label' => 'JSON',
                'ok' => extension_loaded('json'),
                'value' => extension_loaded('json') ? 'ok' : 'missing',
            ],
            'storage_writable' => [
                'label' => 'storage/ writable',
                'ok' => is_writable(storage_path()),
                'value' => is_writable(storage_path()) ? 'yes' : 'no',
            ],
            'bootstrap_cache_writable' => [
                'label' => 'bootstrap/cache writable',
                'ok' => is_writable(base_path('bootstrap/cache')),
                'value' => is_writable(base_path('bootstrap/cache')) ? 'yes' : 'no',
            ],
        ];
    }

    public static function allRequirementsMet(): bool
    {
        foreach (self::requirements() as $check) {
            if (! $check['ok']) {
                return false;
            }
        }

        return true;
    }

    public static function failedRequirementLabels(): array
    {
        $failed = [];
        foreach (self::requirements() as $check) {
            if (! $check['ok']) {
                $failed[] = $check['label'].' ('.$check['value'].')';
            }
        }

        return $failed;
    }

    /**
     * @param  array<string, mixed>  $parameters
     */
    public static function runArtisan(string $command, array $parameters = []): array
    {
        $exitCode = Artisan::call($command, $parameters);

        return [
            'command' => $command,
            'exit_code' => $exitCode,
            'output' => Artisan::output(),
            'success' => $exitCode === 0,
        ];
    }

    public static function testDatabaseConnection(
        string $connection,
        string $host,
        string $port,
        string $database,
        string $username,
        string $password
    ): array {
        try {
            if ($connection === 'pgsql') {
                $dsn = "pgsql:host={$host};port={$port};dbname={$database}";
            } else {
                $dsn = "mysql:host={$host};port={$port};dbname={$database};charset=utf8mb4";
            }

            $pdo = new \PDO($dsn, $username, $password, [
                \PDO::ATTR_ERRMODE => \PDO::ERRMODE_EXCEPTION,
                \PDO::ATTR_TIMEOUT => 5,
            ]);

            $pdo->query('SELECT 1');

            return ['success' => true, 'message' => 'Connection successful.'];
        } catch (\Throwable $e) {
            return ['success' => false, 'message' => $e->getMessage()];
        }
    }
}
